fix macos

diff --git a/.github/workflows/macos-universal2.yaml b/.github/workflows/macos-universal2.yaml
--- a/.github/workflows/macos-universal2.yaml
+++ b/.github/workflows/macos-universal2.yaml
@@ -3,7 +3,7 @@ name: macos-universal2
 on:
   push:
     branches:
-      - v1.22.0-2
+      - test-v1.23.2
   workflow_dispatch:
     inputs:
       version:
@@ -102,6 +102,41 @@ jobs:
           # python3 -m pip install cmake
           cmake --version
 
+      - name: Patch onnxruntime for mlas
+        if: steps.cache-build-result.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          MLAS_CMAKE_FILE="onnxruntime/cmake/onnxruntime_mlas.cmake"
+          if [[ ! -f "$MLAS_CMAKE_FILE" ]]; then
+            echo "Error: $MLAS_CMAKE_FILE not found!"
+            exit 1
+          fi
+
+          cat <<'EOF' >> "$MLAS_CMAKE_FILE"
+            # --- PATCH: Export multi-arch MLAS targets for static builds ---
+            if(ONNXRUNTIME_MLAS_MULTI_ARCH AND NOT onnxruntime_BUILD_SHARED_LIB)
+                if(TARGET onnxruntime_mlas_arm64)
+                    install(TARGETS onnxruntime_mlas_arm64
+                            EXPORT ${PROJECT_NAME}Targets
+                            ARCHIVE   DESTINATION ${CMAKE_INSTALL_LIBDIR}
+                            LIBRARY   DESTINATION ${CMAKE_INSTALL_LIBDIR}
+                            RUNTIME   DESTINATION ${CMAKE_INSTALL_BINDIR})
+                endif()
+                if(TARGET onnxruntime_mlas_x86_64)
+                    install(TARGETS onnxruntime_mlas_x86_64
+                            EXPORT ${PROJECT_NAME}Targets
+                            ARCHIVE   DESTINATION ${CMAKE_INSTALL_LIBDIR}
+                            LIBRARY   DESTINATION ${CMAKE_INSTALL_LIBDIR}
+                            RUNTIME   DESTINATION ${CMAKE_INSTALL_BINDIR})
+                endif()
+            endif()
+            # --- END PATCH ---
+          EOF
+
+          echo "✅ Patched $MLAS_CMAKE_FILE to export multi-arch MLAS targets."
+          cd onnxruntime
+          git diff .
+
       - name: Build onnxruntime for macOS universal2
         if: steps.cache-build-result.outputs.cache-hit != 'true'
         shell: bash
@@ -111,7 +146,7 @@ jobs:
           cmake --version
           export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
 
-          export CMAKE_OPTIONS="-Donnxruntime_USE_COREML=OFF -Donnxruntime_USE_MLAS=OFF -DCMAKE_OSX_ARCHITECTURES='arm64;x86_64' --compile-no-warning-as-error -Donnxruntime_BUILD_UNIT_TESTS=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=$GITHUB_WORKSPACE/bin/protoc"
+          export CMAKE_OPTIONS="-Donnxruntime_USE_COREML=OFF -DCMAKE_OSX_ARCHITECTURES='arm64;x86_64' --compile-no-warning-as-error -Donnxruntime_BUILD_UNIT_TESTS=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=$GITHUB_WORKSPACE/bin/protoc"
           ./build-static_lib.sh
 
       - name: Collect result
